## WiSHFUL Controller's config file

controller:
    name: "Controller"
    info: "WiSHFUL Controller"
    dl: "tcp://127.0.0.1:8990"
    ul: "tcp://127.0.0.1:8989"

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryControllerModule
        kwargs: {"iface":"lo", "groupName":"wishful_1234", "downlink":"tcp://127.0.0.1:8990", "uplink":"tcp://127.0.0.1:8989"}